create database ManageShopOnline
create table product(
ProId varchar(10) primary key,
ProName varchar(50) not null,
ProDescription varchar(500),
ProPrice money check(ProPrice>0),
Stock int check (Stock>0 or Stock=0)
)
/// We create a table and make a foreign key and a ProDescription that describes the product, after that we indicate that the price of the coin is greater than zero
create table Categories(
CateID varchar(10) primary key,
CateName varchar(50) not null,
ProID varchar(10)foreign key references Product(ProID),
CateDescription varchar(500) not null
)
create table Customer(
CusID varchar(10) primary key,
CusName varchar(50) not  null,
CusEmail varchar(50) unique,
CusAddress varchar(100)not null
/// We create a table and make a foreign key, and make it so that the value is non-zero
)
create table Invoice(
InvoiceID varchar(10) primary key,
CusID varchar(10) foreign key references Customer(CusID),
[date] datetime
)
create table Invoice_Product(
InvoiceID varchar(10) foreign key references Invoice(InvoiceID),
ProID varchar(10) foreign key references Product(ProID),
Quantity int check(Quantity>0)
)
/// We create a table in order to determine the number of grocery items and make a link in order to determine the product id
create table Feedback(
CusID varchar(10) foreign key references Customer(CusID),
ProID varchar(10) foreign key references Product(ProID),
comment varchar(300)unique,
[date] datetime
)
/// We create a table in order to determine the feedback, then we make a link for the product key, then we make an identifier for the feedback
create table ManageAccount(
AccName varchar(30) not null,
AccPass varchar(20) not null,
AccPhone varchar(11)not null,
AccAddress varchar(50) not null,
AccEmail varchar(50) unique,
[status] varchar(20) check ([status]='activate' or [status]= 'deactivate')
)
/// We make a table where we determine whether the product has been checked or not, after that we activate the selected product or, conversely, deactivate it

--Insert data into Product
select * from Product
insert into Product values ('P001','Book','New',500,100)
insert into Product values ('P111','Laptop Dell','New',1500,50)
insert into Product values ('P801','Pen','New',3,1000)
insert into Product values ('P246','SmartPhone Iphone','New',1000,25)
insert into Product values ('P456','Fan','New',35,100)
insert into Product values ('P852','Notebook','New',10,500)


--Insert data into Categories
insert into Categories values('Cat03','Laptop','P111','sales up30%')
insert into Categories values('Cat08','Fan','P456','sales,'upto 20%')
insert into Categories values('Cat13','Laptop','P111','sales up30%')
insert into Categories values('Cat30','Laptop','P111','sales up30%')
insert into Categories values('Cat32','Laptop','P111','sales up30%')
/// We specify the product category and its value, where we determine how much the discount will be on sale

--Insert data into Customer
insert into Customer values('Cus111','Naman','2416546465','naman@gmail.com','Bihar')
insert into Customer values('Cus123','Nipun','2416421465','nipun@gmail.com','Uttarakhand')
insert into Customer values('Cus114','Nitin','1116546465','nitin@gmail.com','Haridwar')
insert into Customer values('Cus162','Visha','9416546465','vishal@gmail.com','Bhagalpur')
insert into Customer values('Cus154','Saran','2452546465','saran@gmail.com','Bihar')
insert into Customer values('Cus168','kishl','4826546465','kishl@gmail.com','Muzaffarpur')
insert into Customer values('Cus111','Naman','2416546465','naman@gmail.com','Bihar')
insert into Customer values('Cus111','Naman','2416546465','naman@gmail.com','Bihar')
/// We point to the value and leave a link to the client's email

--Insert data into Invoice
insert into Invoice values('I162','Cus111','4/12/2022')
insert into Invoice values('I168','Cus168','4/10/2022')
insert into Invoice values('I154','Cus154','4/15/2022')
insert into Invoice values('I123','Cus123','4/09/2022')
insert into Invoice values('I114','Cus114','4/16/2022')


--Insert data into Invoice_Product
insert into Invoice_Product('I162','P111',2)
insert into Invoice_Product('I168','P246',1)
insert into Invoice_Product('I154','P852',5)
insert into Invoice_Product('I123','P977',5)
insert into Invoice_Product('I114','P456',15)
/// Указываем на продукт и показываем на его счёт
--Insert data into Feedback
insert into Feedback values('Cus162','P852','it is good','4/1/2022')
insert into Feedback values('Cus168','P111','it is good','4/5/2022')
insert into Feedback values('Cus154','P246','it is good','4/6/2022')
insert into Feedback values('Cus123','P977','it is good','4/2/2022')
insert into Feedback values('Cus114','P456','it is good','4/4/2022')
/// We receive feedback and return the value on the specified date and this is a good event for us

--Insert data into ManageAccount
insert into ManageAccount values('naman','CH0503','0985463254','naman@gmail.com','activate')
insert into ManageAccount values('nipun','123456','4528763254','nipun@gmail.com','deactivate')
insert into ManageAccount values('nitin','452583','3256463254','nitin@gmail.com','activate')
///We display the account in the messenger and the value assigned to them, and we also activate the mail



